{% set name = "pythonradex" %}
{% set version = "1.0.8" %}
{% set python_min = "3.10" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/pythonradex-{{ version }}.tar.gz
  sha256: 6b309e51a12737129c7ff3a8d7ec778f357d4cddbf34fa4da5800708ce6341d1

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - hatchling
    - pip
  run:
    - python >={{ python_min }}
    - scipy >=1.14
    - numpy >=2.0
    - numba >=0.61.0

test:
  imports:
    - pythonradex.radiative_transfer
    - pythonradex.LAMDA_file
    - pythonradex.helpers
    - pythonradex.molecule
  requires:
    - pip
    - pytest
  source_files:
    - src/
    - tests/
  commands:
    - pip check
    - pytest ./tests

about:
  home: https://pypi.org/project/pythonradex/
  summary: 1D non-LTE radiative transfer
  dev_url: https://github.com/gica3618/pythonradex
  license: MIT
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - gica3618
